<?php

return [
    'access'=>[
        'list-category'=>'category_list',
        'add-category'=>'category_add',
        'edit-category'=>'category_edit',
        'delete-category'=>'category_delete',
        'list-menu'=>'menu_list',
        'add-menu'=>'menu_add',
        'edit-menu'=>'menu_edit',
        'delete-menu'=>'menu_delete',
        'list-product'=>'product_list',
        'add-product'=>'product_add',
        'edit-product'=>'product_edit',
        'delete-product'=>'product_delete',
        'list-slider'=>'slider_list',
        'add-slider'=>'slider_add',
        'edit-slider'=>'slider_edit',
        'delete-slider'=>'slider_delete',
        'list-setting'=>'setting_list',
        'add-setting'=>'setting_add',
        'edit-setting'=>'setting_edit',
        'delete-setting'=>'setting_delete',
        'list-user'=>'user_list',
        'add-user'=>'user_add',
        'edit-user'=>'user_edit',
        'delete-user'=>'user_delete',
        'list-role'=>'role_list',
        'add-role'=>'role_add',
        'edit-role'=>'role_edit',
        'delete-role'=>'role_delete'
    ],
    'table_module'=>[
        'category',
        'slider',
        'product',
        'setting',
        'menu',
        'user',
        'role'
    ],
    'module_children'=>[
         'list',
         'add',
         'edit',
         'delete'
    ]
];


